# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CD

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cdk

    # permission can be added at job level or workflow level
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 8
          run_install: |
            - args: [--global, aws-cdk]

      - name: Use Node.js Lts
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - name: Install CDK dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::637423394100:role/Test3GitHubActions
          aws-region: ap-northeast-1

      - name: Deploy CDK
        run: cdk deploy --require-approval never

  # https://www.apollographql.com/docs/graphos/delivery/publishing-schemas/
  # https://www.apollographql.com/docs/rover/ci-cd/#github-actions
  publish-schema:
    name: Publish Schema
    runs-on: ubuntu-latest
    env:
      APOLLO_KEY: ${{ secrets.APOLLO_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/v0.23.0 | sh

          # Add Rover to the $GITHUB_PATH so it can be used in another step
          # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      - name: Publish Schema
        run: |
          rover subgraph publish test3-hnwxwf@current --name test3 --schema src/schema.gql --routing-url https://api.u-ran.com/graphql
