# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CD

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # permission can be added at job level or workflow level
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js lts
        uses: actions/setup-node@v4
        with:
          node-version: lts

      - name: Install CDK dependencies
        run: |
          npm i -g pnpm
          npm i -g cdk
          cd cdk
          pnpm install --frozen-lockfile

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::637423394100:role/Test3GitHubActions
          aws-region: ap-northeast-1

      - name: Deploy CDK
        run: cdk deploy --require-approval never
